name: Issue
on:
  issues:
    types:
      - opened

jobs:
  extract-and-create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract branch name from issue body
        id: extract-branch
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_NAME=$(echo "$ISSUE_BODY" | awk '/🔀 브랜치명 \(branch\)/ {getline; getline; print}' | sed 's/^ *//; s/ *$//')
          echo "ISSUE_NAME=$ISSUE_NAME" >> $GITHUB_ENV

      - name: Create a branch for the issue
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}